### ISSUE TITLE
Weapon Refinement Recognition

### ISSUE THREAD

**Issue by RSvlad** [Andrewthe13th/Genshin_Scanner#1]
Once I scan and check the file, all weapons are listed as R1 weapons.

**Comment by Andrewthe13th** [comment]
Is it when you enter it into Genshin Optimizer? Looking at my json it does state my refinements
![Screenshot 2021-09-17 090802](https://user-images.githubusercontent.com/11446437/133819914-471fe7d8-33f3-44b7-90e6-ea33bbcf01e3.png)

**Comment by RSvlad** [comment]
It was GO. My mistake, I looked at the level in the json file instead of refinement, and GO seems to have trouble reading the ref

**Comment by RSvlad** [comment]
I've restarted my browser and the ref on my claymore is back to normal, was pretty weird

**Comment by Andrewthe13th** [comment]
Ya the devs at Genshin Optimzer fixed the issue
