### ISSUE TITLE
Scanned image not start at the right offset 

### ISSUE THREAD

**Issue by mamatom** [Andrewthe13th/Genshin_Scanner#10]
Version: v0.8

scanned image not start at the right offset.
i'm using ultra wide monitor with 2560 * 1080 resolution(the game is at 1280 * 720). not sure if it's the cause.

![image](https://user-images.githubusercontent.com/44089040/135719380-9c9930ac-0676-4141-aae0-537e4714a104.png)

**Comment by Andrewthe13th** [comment]
Yea it works with my ultra wide. 3440 by 1440. So when this happens you need to restart genshin impact and the scanner. This happens rarely tho.

**Comment by mamatom** [comment]
It's working now, Thanks a lot!
Here are still some minor issues that i encountered while using it.
- Dark Iron Sword 's key is incorrect .
- Scanner sometimes miss the first artifact in the row.
- Sometime there's a lag spike while scrolling and it skip an entire row.

**Comment by Andrewthe13th** [comment]
ok thanks for the feedback.
