### ISSUE TITLE
Issues and Feature Requests

### ISSUE THREAD

**Issue by Alb11747** [Andrewthe13th/Genshin_Scanner#11]
Issues:
- When weapon and artifact scanning sometimes scrolling doesn't work and double scans the same item.
- Sometimes doesn't scan characters and just stops.
- Doesn't detect the Traveler name correctly. (Error Log: "Error: [Traveler] is not a valid Character Name")
- Pressing enter to stop sometimes doesn't work. / Blocks the ability to press enter in other applications when not scanning sometimes. (Most Likely due to KeyboardHook / KeyHandler)
Feature Request:
- Togglable scanning of Weapon, Artifact, and Characters with a checkbox
- Check for doubled artifacts and weapons

**Comment by Andrewthe13th** [comment]
So am still working on trying to add a user defined delay system cause it might run too fast for inputs to register. That will fix scrolling and the character scanner from stopping. If you could share me your traveler name so I could test it, that would be great. I will look into 'enter' key bug, as I might have broken it in this patch. Will add a checklist for weapon/artifact/characters. I don't think I need a check for double artifacts and weapons as I believe my inputs were too fast and will be solved by user defined delay system.

**Comment by Alb11747** [comment]
Traveler Name: Alb11747

**Comment by flover2102** [comment]
scane artefact work but for me app crash after scaning last character , when artéfact are at ~500/840

**Comment by Andrewthe13th** [comment]
ok. I thought I had a check to wait for artifacts to finish scanning after characters. Thanks for reporting.

**Comment by Andrewthe13th** [comment]
It requires admin access due to use keyboard/mouse simulation.
