### ISSUE TITLE
No file creation (Possible Issue with player name)

### ISSUE THREAD

**Issue by fl2357** [Andrewthe13th/Genshin_Scanner#12]
Hi There,

I cannot seem to get the program to create a JSON file for output, it scans through fine however no file is created. Unless I am very dense and completely missed it.

I think this may be an issue with my player name "Shogun'sSimp" as I did get an error once "Shogun'sSimp is an invalid name" the name itself was a funny joke at the time and now I am stuck with it until we can change our names/sig again.

**Comment by fl2357** [comment]
im dense

**Comment by Andrewthe13th** [comment]
what was the solution?

**Comment by fl2357** [comment]
I ran it again and it worked this time and the file was correctly located in the mydocs folder. (Might wanna mention the JSON file goes there as I initially was looking in the Genshin_Scanner folder.
