### ISSUE TITLE
aquilafavonia is not a valid Weapon Name

### ISSUE THREAD

**Issue by Qumojo** [Andrewthe13th/Genshin_Scanner#14]
Awesome app, great job. Just one issue, you've got listed "Aquil/i/a Favonia" in your list instead as "Aquila Favonia". As well as having issue to get chars listed correctly, I've got mainly issues with Sayu it seems, but I've read in previous posts that you're already working on that issue. Would be great to have check box next to chars/weapons/artefacts to re-run scans if one fails for something and try again only that one instead of getting again 1000 artefacts and 200 weapons, if only chars failed.
Thanks a lot for your great work, can't wait for next update <3

**Comment by Andrewthe13th** [comment]
Ah i misspelled it. haha. Thanks for the report
