### ISSUE TITLE
Error Log - not a valid set name/characters not scanning

### ISSUE THREAD

**Issue by SethingtonSteel** [Andrewthe13th/Genshin_Scanner#15]
Thanks for the program, really enjoying it. 

Was running into issues scanning all of my characters, I think it was because after I changed my resolution I moved the program slightly, as after restarting Genshin and leaving it in place, it scanned everything perfectly

Other than the small issue with character scans this was the only other error I came across - 
Error: Error: prayerstospringtime is not a valid Set Name

**Comment by Andrewthe13th** [comment]
Thanks for reporting.
![image](https://user-images.githubusercontent.com/11446437/136666452-16af763a-339c-4419-a135-f43b3bc63680.png)
I see the issue. Thought it was supposed to be for lol.

**Comment by SethingtonSteel** [comment]
Ahh nice one, I've been doing a lot of artifact farming since and its just stopped scanning past my first character entirely now, even after restarting. here are some more error log entries too 

Error: Found instead of Weapon Level.
Error: mysticenhancementore is not a valid Weapon Name

**Comment by Andrewthe13th** [comment]
Ya. Its a known issue. Ill be trying to fix it for next release.
