### ISSUE TITLE
Program crashes after scanning a few weapons

### ISSUE THREAD

**Issue by positionV** [Andrewthe13th/Genshin_Scanner#2]
1. 1280 windowed as instructed
2. No flux or filters active
3. Crashes after scanning 15-16 weapons (R3 serpent spine or R5 festering desire)

Please let me know any additional info you require

**Comment by Andrewthe13th** [comment]
Thanks for the info. I'll look into it. I will be working to make my system alot more accepting of scanner failure and provide a error log to better pin point errors. If you could provide a screenshot of ur weapon inventory it would help me to determine which weapon it crashed on.

**Comment by positionV** [comment]
![image](https://user-images.githubusercontent.com/90944079/133870168-93437a0e-7b58-438b-94e0-979d3ffaf8bf.png)
Crashed on serpent spine like 2-3x, festering like 5x, and black sword like once. The program exist itself when it crashes. No error message. The picture I've attached is in 1600x900 windowed, but I ran the program in the 1280 windowed as instructed.

**Comment by Andrewthe13th** [comment]
Next release will fix your issue which I will release sometime tomorrow. Primordial Jade Winged-Spear was the issue.

**Comment by positionV** [comment]
Cool! Thanks for the quick follow up!

**Comment by Andrewthe13th** [comment]
Just released the newest patch.Try it out whenever you have the chance. Please let me know if it worked for you. If not, it should not crash and say why it did.

**Comment by WantYouGone** [comment]
![image](https://user-images.githubusercontent.com/37950449/133918152-4383b729-8c81-43aa-8279-e5ee5c1f45a5.png)
It crashed for me, this is what I got.

**Comment by Andrewthe13th** [comment]
I see my weaponlist has that weapon name misspelled. I just listed as TheViridescent. Without Hunt. Will double check weapon names again. Thanks for posting.

**Comment by positionV** [comment]
I can confirm the above error posted by WantYouGone
![image](https://user-images.githubusercontent.com/90944079/133931324-227f291b-2ab2-4811-a46e-ebc30feac4f1.png)

**Comment by Andrewthe13th** [comment]
Posted a new version that will bypass errors. So you can get a file regardless of error occurred along the way. Thanks for using my scanner guys. It also should work for the TheViridescentHunt now.

**Comment by flover2102** [comment]
app crash at artefact (app close) after 2 ligne

**Comment by flover2102** [comment]
yes and crash at artefct , i have try to record it but whene i record app crash whene i click on button , 

i have see my cpu go to 70% so maybe app is to fast idk

**Comment by Andrewthe13th** [comment]
ok. its prob crashing when reading your artifact count. Will look into it. Thanks

**Comment by Dranixx** [comment]
Yeah same for me, the program crash on artifarcts after reading the first line, it scroll down, read some artifacts (a few it's random) and crash.
