### ISSUE TITLE
Crash at scan completion

### ISSUE THREAD

**Issue by LuceneDrift** [Andrewthe13th/Genshin_Scanner#21]
Hey there, having a problem completing a scan. The app seems to finish checking everything but then crashes, this is what I see in the application event log. Genshin is the Epic version, not running on the C drive if that makes a difference. Tried running this a few times and from various locations inc the game directory.

Any help appreciated :)

.net runtime error 

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-10-11T17:06:13.0226698Z" /> 
  <EventRecordID>83032</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>Computer</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Application: GenshinGuide.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.IO.FileNotFoundException at System.IO.__Error.WinIOError(Int32, System.String) at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean) at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean) at System.IO.StreamWriter.CreateFile(System.String, Boolean, Boolean) at System.IO.StreamWriter..ctor(System.String, Boolean, System.Text.Encoding, Int32, Boolean) at System.IO.StreamWriter..ctor(System.String, Boolean) at GenshinGuide.Scraper.CreateJsonFile(GenshinGuide.GOOD) at GenshinGuide.Form1.<button1_Click>b__8_0() at System.Threading.ThreadHelper.ThreadStart_Context(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.ThreadHelper.ThreadStart()</Data> 
  </EventData>
  </Event>

Then application error

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-10-11T17:06:13.6719319Z" /> 
  <EventRecordID>83033</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>Computer</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>GenshinGuide.exe</Data> 
  <Data>1.0.0.0</Data> 
  <Data>b9c34461</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.19041.1202</Data> 
  <Data>448a4f5d</Data> 
  <Data>e0434352</Data> 
  <Data>0012b5b2</Data> 
  <Data>3364</Data> 
  <Data>01d7bec1e3758881</Data> 
  <Data>C:\Users\Username\Documents\Genshin_Scanner_V0.8\GenshinGuide.exe</Data> 
  <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data> 
  <Data>bde2fd7f-042a-49d2-9909-331080e977bf</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by Andrewthe13th** [comment]
Exception Info: System.IO.FileNotFoundException at System.IO. I dont know why it would fail to find file since i make it create file if file doesn't exist. I will look at my code for issues. Thanks for reporting.
