### ISSUE TITLE
Error scanning weapons

### ISSUE THREAD

**Issue by fivetail** [Andrewthe13th/Genshin_Scanner#27]
First of all, thank you so much for creating such an amazing tool!

I'm using Windows 10 64-bit. The scanner used to work perfectly. I foolishly interrupted the scanning by force-closing the program (I didn't know to press Enter to stop it), and since then, it has been unable to scan weapons at all.

I have tried restarting my computer, and changing the directory to which the JSON is saved. I have tried wiping the program + its existing JSON files from my system and redownloading it, as well as downloading older versions. It still skips over weapons each time when beginning the scan. When I use the latest version and only tick "Weapons" to be scanned, I get a Windows error saying the scanner encountered an unexpected error and has to close:

![Untitled.](https://user-images.githubusercontent.com/9046677/137648951-39d7f379-1598-4a8d-9da9-50172b208664.png)

Is there something else in my computer I can "clear" or reset to try and get it working again?

Thank you!

**Comment by Andrewthe13th** [comment]
interesting. Have you tried restarted genshin? There is a known issue with the screen capture no being center for some reason. The only way to fix that is to reset genshin.

**Comment by fivetail** [comment]
Thank you for the quick reply! I have tried restarting Genshin before this, but keeping the resized game window dead-center of my monitor before starting the scan worked! Thank you for your help.
