### ISSUE TITLE
Scanner crash during artifacts scan

### ISSUE THREAD

**Issue by Dranixx** [Andrewthe13th/Genshin_Scanner#3]
Version: v0.7
Settings: 1280x720 Windowed - English - Keyboard

- The program crash at the middle of artifacts scan.
- The OCR seems not working properly for weapons
`Error: Found instead of Weapon Level.  `
`Error: AmOSBow is not a valid Weapon Name`
`Error: Found instead of Weapon Level.`
`Error: MistsplitterKetTorged is not a valid Weapon Name`
- And when I press ENTER to stop the scanner, it throw an exception, don't know if it's the expected behavior.

**Comment by Andrewthe13th** [comment]
ok thanks for posting

**Comment by flover2102** [comment]
0.7 
crash after 5 lign of artefact

**Comment by Andrewthe13th** [comment]
ok.
