### ISSUE TITLE
Error: thoma is not a valid Character Name

### ISSUE THREAD

**Issue by neorus616** [Andrewthe13th/Genshin_Scanner#46]
thoma is not in DB?

**Comment by Andrewthe13th** [comment]
yea no thoma in yet unfortunately. I guess i forgot about the update since i dont care about hu tao lol.

**Comment by hastarin** [comment]
> yea no thoma in yet unfortunately. I guess i forgot about the update since i dont care about hu tao lol.

Is it just a matter of adding his name to GOOD.cs? Or does it require some training for OCR as well?

BTW Thanks for the app, as someone new to Genshin it's proving quite handy in combination with Genshin Optimizer.

**Comment by Andrewthe13th** [comment]
So I just need to add Thoma to character list in lowercase in Scraper.cs then add however Thoma is spelled in GO to GOOD.cs. I just can't do right as my working version isn't complete d yet. Implementing more features right now.

**Comment by hastarin** [comment]
> So I just need to add Thoma to character list in lowercase in Scraper.cs then add however Thoma is spelled in GO to GOOD.cs. I just can't do right now as my working version isn't completed yet. Implementing more features right now.

Thanks, I can always build my own copy with those changes in the meantime then. 👍

**Comment by hastarin** [comment]
[thoma.zip](https://github.com/Andrewthe13th/Genshin_Scanner/files/7491413/thoma.zip)
I've attached a zip of a patch file to do the above. It also adds the tessdata file to the project which would fix #45
