### ISSUE TITLE
Unable to scan character Sangonomiya Kokomi, talent level of Mona and Ayaka's burst are incorrect

### ISSUE THREAD

**Issue by nguyenhung9697** [Andrewthe13th/Genshin_Scanner#5]
I'm using version 0.7, settings are 
- Graphics: 1280x720 Windowed
- Language: English 
- Control: Keyboard

The scanner scans every just fine, except for: 
- Dark Iron Sword, which was reported in #4 
- Sangonomiya Kokomi: give message "Error: Character Name and Element are wrong" 
- Mona's Stellaris Phatasm and Ayaka's Kamisata Art: Soumetsu's level are incorrect. The scanner scan their Alternate Sprint skill's level (which is always 1) instead. Unlike other characters, their burst skills are at 4th place from the top, not 3rd.
![image](https://user-images.githubusercontent.com/13299300/134803528-7e5f67ba-9032-4f02-b70d-29d1d3a17d6d.png)

Thank you for creating this tool and make it open source. Have a good day.

**Comment by Andrewthe13th** [comment]
Thanks for the report. I indeed did not account for mona and ayaka skills placement. Will fix for next patch. I will look into the error for kokomi
