### ISSUE TITLE
Artifacts are not scanning. And the system scans the total number of wrong artifacts as well.

### ISSUE THREAD

**Issue by jchojjjjj** [Andrewthe13th/Genshin_Scanner#55]

**Comment by Cupcak3** [comment]
This is has been reported. Can you post a screenshot of the top right of your inventory where it says `Artifacts xxxx / 2000`?

**Comment by jchojjjjj** [comment]
`Artifacts 0 / 18`

![image](https://user-images.githubusercontent.com/84227375/142390658-3dac814f-8063-407e-9c59-256572662967.png)

Sorry, I'm late.

**Comment by jchojjjjj** [comment]
> _No description provided._
