### ISSUE TITLE
C6 on all chars and didn't scan weapons properly

### ISSUE THREAD

**Issue by NinjaShuriken** [Andrewthe13th/Genshin_Scanner#57]
When the tool scanned my characters it gave constellation 6 to every one of them, it also only scanned 19/42+ weapons I have

**Comment by Andrewthe13th** [comment]
make sure to turn off NVIDIA color filters are anything of the sort. Constellation is determined by color. I am fixing weapon count on my part.

**Comment by NinjaShuriken** [comment]
Ah, alright this was my bad I do have Nvidia freestyle enabled on Genshin, will try again
