### ISSUE TITLE
Error when exporting Viridiscent Hunt (BP bow)

### ISSUE THREAD

**Issue by jajobaucas** [Andrewthe13th/Genshin_Scanner#6]
Genshin Optimizer (https://frzyc.github.io/genshin-optimizer/#/database) expects "TheViridescentHunt" as bow name, but exporter uses the name "TheViridescent"
GOOD data here: https://pastebin.com/3yGe62Tg

**Comment by Andrewthe13th** [comment]
Thanks for reporting. I do have a misspelling in my exporter for Genshin Optimizer
